overtime:
    path: /overtime/{hotel_id}
    methods: get
    controller: App\Controller\ApiController::overtime

benchMark:
    path: /benchmark/{hotel_id}
    methods: get
    controller: App\Controller\ApiController::benchMark
